# Generated by Django 5.2.4 on 2025-08-03 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0010_rename_full_name_student_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentIssueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_issued', models.PositiveIntegerField()),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('status_from_student', models.CharField(choices=[('Issued', 'Issued'), ('Returned', 'Returned'), ('Need More Time', 'Need More Time')], default='Issued', max_length=20)),
                ('status_from_teacher', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Returned', 'Returned')], default='Pending', max_length=20)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.component')),
                ('full_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_full_name', to='base.student')),
                ('roll_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_roll_number', to='base.student')),
            ],
        ),
    ]
