# Generated by Django 5.2.4 on 2025-08-04 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_full_name_student_full_name'),
        ('student_dash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentissuelog',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='studentissuelog',
            name='roll_number',
        ),
        migrations.AddField(
            model_name='studentissuelog',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentissuelog',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentissuelog',
            name='status_from_student',
            field=models.CharField(blank=True, choices=[('Issued', 'Issued'), ('Returned', 'Returned')], max_length=20, null=True),
        ),
    ]
