# Generated by Django 5.2.4 on 2025-08-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dash', '0002_remove_studentissuelog_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentissuelog',
            name='status_from_student',
            field=models.CharField(blank=True, choices=[('Requested', 'Requested'), ('Issued', 'Issued'), ('Returned', 'Returned')], max_length=20, null=True),
        ),
    ]
