# Generated by Django 5.2.4 on 2025-08-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dash', '0003_alter_studentissuelog_status_from_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentissuelog',
            name='form_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
