# Generated by Django 5.2.4 on 2025-08-06 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_full_name_student_full_name'),
        ('student_dash', '0004_studentissuelog_form_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentissuelog',
            name='studentid',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='sid_fromtable', to='base.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentissuelog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sname_fromtable', to='base.student'),
        ),
    ]
