# Generated by Django 5.2.4 on 2025-08-06 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_full_name_student_full_name'),
        ('student_dash', '0005_studentissuelog_studentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentissuelog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.student'),
        ),
    ]
