# Generated by Django 5.2.4 on 2025-08-06 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_full_name_student_full_name'),
        ('student_dash', '0006_alter_studentissuelog_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentissuelog',
            name='studentid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sid_fromtable', to='base.student'),
        ),
    ]
