# Generated by Django 5.2.4 on 2025-08-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dash', '0007_alter_studentissuelog_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentissuelog',
            name='status_from_student',
            field=models.CharField(blank=True, choices=[('Requested', 'Requested'), ('Issued', 'Issued'), ('Returned', 'Returned'), ('Rejected', 'Rejected')], max_length=20, null=True),
        ),
    ]
