# Generated by Django 5.2.4 on 2025-07-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(choices=[('Microcontroller', 'Microcontroller/Board'), ('Sensor', 'Sensor'), ('Actuator', 'Actuator'), ('Electronic', 'Electronic Component'), ('Display', 'Display'), ('Misc', 'Miscellaneous')], max_length=20)),
                ('date_received', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='host',
        ),
        migrations.RemoveField(
            model_name='room',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
