# Generated by Django 5.2.4 on 2025-07-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='tanuj',
            field=models.TextField(null=True),
        ),
    ]
