# Generated by Django 5.2.4 on 2025-07-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_comp', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(choices=[('Microcontroller', 'Microcontroller/Board'), ('Sensor', 'Sensor'), ('Actuator', 'Actuator'), ('Electronic', 'Electronic Component'), ('Display', 'Display'), ('Misc', 'Miscellaneous')], max_length=20)),
            ],
        ),
    ]
