# Generated by Django 5.2.4 on 2025-07-30 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_componenttable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComponentTable',
            new_name='Component',
        ),
    ]
