# Generated by Django 5.2.4 on 2025-07-30 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_issuerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='date_received',
        ),
    ]
