# Generated by Django 5.2.4 on 2025-07-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_room_tanuj'),
        ('base', '0004_student_password'),
    ]

    operations = [
    ]
