# Generated by Django 5.2.4 on 2025-07-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_component_date_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='date_of_purchase',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
    ]
