# Generated by Django 5.2.4 on 2025-07-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        
        ('base', '0004_student_password'),
        ('base', '0006_component_date_of_purchase'),
    ]

    operations = [
    ]
