# Generated by Django 5.2.4 on 2025-08-01 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_student_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='full_name',
            new_name='Full_name',
        ),
    ]
