# Generated by Django 5.2.4 on 2025-08-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_full_name_student_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Full_name',
            new_name='full_name',
        ),
    ]
