# Generated by Django 5.2.4 on 2025-08-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_full_name_student_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='componentstatus',
            field=models.CharField(choices=[('Defective', 'Defective'), ('Deleted', 'Deleted'), ('working', 'working')], default='working', max_length=20),
        ),
    ]
