# Generated by Django 5.2.4 on 2025-08-31 15:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_component_componentstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('resent_count', models.PositiveSmallIntegerField(default=0)),
                ('session_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
